### PR TITLE
Convert to noarch

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
:+1: From me, I would think the linter can be ignored.

**Comment by dbast** [comment]
Should we move also `- xorg-libxfixes  # [linux]` from host to build?

**Comment by dpryan79** [comment]
Yes, that would make sense.

**Comment by dbast** [comment]
It builds and the linter is fine.

But is it also technically correct? Meaning we do not build/link against `xorg-libxfixes` and also don't want conda to install it for us during package install on user side, because the user has anyway a complete xorg install on system level?

**Comment by dpryan79** [comment]
I think the more X stuff we try to ship the more likely we are to cause problems with the existing X install on people's machines.

**Comment by dbast** [comment]
Ok. So I guess this is ready to be merged.

**Review by jdblischak — APPROVED** [review]
Since there are no longer selectors in "host" or "run", I think it's fine to be converted to a noarch recipe.

**Pull request merged**
